### PR TITLE
redis: Support a few more socket_* options

### PR DESCRIPTION
**Pull request by kajinamit**
This introduces a native interface to tune socket_* options in Redis client.

### CODE REVIEW

**Comment by kajinamit** [comment]
note: These options have been available since redis-py 2.10.0, which is very old, so I didn't explicitly document the version requirement.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision adf7a8ab56fd00ed2b5da7fff655cdee601cb87d of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change adf7a8ab56fd00ed2b5da7fff655cdee601cb87d: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/5155

**Comment by zzzeek** [comment]
thanks, will see if this can be for 1.3.2 along with a new RedisCluster backend.

**Comment by zzzeek** [comment]
in the gerrit (not here) Ive rebased to main to pick up RedisClusterBackend and also did some doc format changes.   https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/5155   if it passes I'll release today

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/5155 has been **merged**. Congratulations! :)

**Pull request closed without merging**
