### PR TITLE
Add py.typed marker and include it in package data

### LINKED ISSUE #238: Add py.typed marker
It looks like dogpile does use type annotations internally, is there a reason why they are not being exported? The package needs to include a `py.typed` marker file for mypy to recognize that it may use the type annotations, otherwise it will treat the package as untyped.

### PR DESCRIPTION
**Pull request by Daverball**
This resolves #238

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 345e6cf4612e8080c8e6a86fb7f03a65bfc006ad of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 345e6cf4612e8080c8e6a86fb7f03a65bfc006ad: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4624

**Comment by zzzeek** [comment]
thanks!

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4624

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4624 has been **merged**. Congratulations! :)

**Pull request closed without merging**
