### PR TITLE
removed legacy py2 __future__ directive

### PR DESCRIPTION
**Pull request by jvanasco**
see #243

### CODE REVIEW

**Comment by zzzeek** [comment]
that was the only one?  OK

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 6daee2f93b1d1fbc718cef43df9ebb69a6ecd1a3 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 6daee2f93b1d1fbc718cef43df9ebb69a6ecd1a3: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4876

**Comment by jvanasco** [comment]
For this, yes.

I did a second check, and there are two files with:

    from __future__ import with_statement

That has been standard since Python 2.6

I can drop those in this PR or do another.

**Comment by zzzeek** [comment]
just update this PR with new commits

**Comment by jvanasco** [comment]
done.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 84ec3268cbec16694d5faf8835cdcc12045028ed of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 84ec3268cbec16694d5faf8835cdcc12045028ed added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4876

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4876

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4876 has been **merged**. Congratulations! :)

**Pull request closed without merging**
