### PR TITLE
Add feature region.key_is_locked()

### LINKED ISSUE #101: feature suggestion - `region.is_key_locked(key)`
**Migrated issue, originally created by jvanasco ([jvanasco](https://github.com/jvanasco))**

I wavered on proposing this for a few days, and am leaning towards this idea. 

It would be useful for those who are dealing with expensive value generators to query a region and see if an active dogpile lock exists for a given key.   (which would then need to be implemented on the backends as well, returning a boolean or perhaps the seconds remaining)

the rationale is that expensive/long-running generators still result in a pileup of processes that are just waiting for a bottleneck to passes.  in some known instances, you may want to handle this.

There are other ways around this, I'm using a few myself.  This just seems like it would be useful.

### PR DESCRIPTION
**Pull request by bagerard**
It checks the lock existence in a non-invasive way

Fixes #101

### CODE REVIEW

**Comment by zzzeek** [comment]
great!  very nice, let's put it in review

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision ceee2d6c10e367f17e226d173d9794404062dd4f of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change ceee2d6c10e367f17e226d173d9794404062dd4f: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2508

**Comment by bagerard** [comment]
BTW @zzzeek just being curious but is there any particular reason for using jenkins/gerrit or is that more historical? In fact from what I understand there is some manual trigger required to run the CI which is OK but is quite unusual

**Comment by zzzeek** [comment]
the manual trigger is because I run the CI servers myself so I dont want to publish an open executable platform.    Gerrit is my preferred code review platform by a mile, I'm not familiar w/ any cloud-based code review tool that is nearly as collaborative.   Jenkins allows for the highly customized environment I need without any chance of it breaking suddenly (matrix builds, we run about fifteen different database servers in containers, etc).

now that we run containers we are in the area where I could *begin* to think about how to use cloud entirely for our CI but the fact remains that I need pretty beefy CI servers to run databases like Oracle and SQL Server.

I wrote a bunch about gerrit some years back at https://techspot.zzzeek.org/2016/04/21/gerrit-is-awesome/ and I'd be interested in hearing what's changed since then, most importantly the easily ability for me to jump in and share patches on any particular code review.  Github PR's I think have some ability for this now but it still does not seem to be apparent to me where it is.   If someone sends me code in a PR I need to have control over that code without any friction.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 8a5ec7aa07dbdfc654617632ffffae6834078263 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 8a5ec7aa07dbdfc654617632ffffae6834078263 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2508

**Comment by bagerard** [comment]
Alright, thanks for elaborating. I must admit that I wasn't familiar with the way of working of Gerrit but I'll check it out. I understand and I guess it makes sense to have that optimized for you as you are the one spending the most time on it. I'll take this opportunity to thank you for the SQLAlchemy project, we use it a lot and it's just **awesome** :+1:

**Comment by zzzeek** [comment]
thanks!   re: gerrit, I went through a lot of effort to shield the outside world from it, as it defintely has a learning curve and I wouldn't want hundreds of accounts on my gerrit server in any case, so outside folks sending PRs that I can then pull into my own "workshop" is a completely ideal workflow for me.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

great job, thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2508

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2508 has been **merged**. Congratulations! :)

**Pull request closed without merging**
