### PR TITLE
Add pymemcached backend

### PR DESCRIPTION
**Pull request by moisesguimaraes**
Adds dogpile.cache.pymemcache based on pymemcache <https://github.com/pinterest/pymemcache>.

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 5bc9488566685b0987216e41e6ec861368da9756 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5bc9488566685b0987216e41e6ec861368da9756: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 29ec25a62218932e07a33829dc74b148f16d4795 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 29ec25a62218932e07a33829dc74b148f16d4795 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by jvanasco** [comment]
IMHO, a few small comments:

1. The docstring for the class should note this utilizes the hash client. 
2. The docstring for init only mentions `tls_context `, and doesn't mention the params for `serde` and `default_noreply`

I'm not familiar with pymemcache, but looking at their docs/source should `pymemcache.serde.pickle_serde` be the default `serde` argument for this library?  If the value were `None`, pymemcache would default to a different item - their Legacy serde.  I don't have a personal opinion on what the default is, BUT if this implementation specifies a default then I do have a strong opinion that should be disclosed in the docstring/apidocs.

**Comment by moisesguimaraes** [comment]
@jvanasco, I was initially not passing a serde or a default_noreply, but I had to add those in order for all tests to pass. I was mostly inspired by the [new Django backend using pymemcache](https://github.com/django/django/blob/master/django/core/cache/backends/memcached.py#L231-L242) when fixing the tests.

The base client only accepts a single server. The HashClient can accept a list of servers like the other memcached backends in dogpile.cache.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

hey Morgan were you looking for this at some point?

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by jvanasco** [comment]
@moisesguimaraes That all sounds fine. Sorry to not be more clear about this: my main concern is that your PR makes some "decisions" about implementing the library, without disclosing those decisions in the docs.  If you think something is the right/best decision - great! That saves the rest of us from having to learn that library!

While **we** are likely to read the source, a lot of users will opt directly for the auto-generated docs (https://dogpilecache.sqlalchemy.org/en/latest/api.html#memcached-backends). Assuming a user is familiar with pymemcached, or having troubleshooting problems, there should be a useful disclosure on those docs that says something like "This library invokes the Hash backend from the upstream library, uses these defaults, and these kwargs will be passed onwards".  Otherwise they're likely to fight a lot with their code before taking a look at the dogpile source.

**Comment by moisesguimaraes** [comment]
@jvanasco I updated the docs, let me know if that works.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

> Patch Set 4:
> 
> moisesguimaraes@github wrote:
> 
> @jvanasco I updated the docs, let me know if that works.
> 
> edit: I sent the review via Gerrit, so it might take a moment to be reflected in here.

the actual code changes only go in one direction (comments are bidirectional) :)  so we're in the gerrit now.   forgot you had access.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

Code-Review+1

Code LGTM. 

@moises would you mind if I did a patch, or if you were inclined, to change the docstring:

= :param tls_context: optional TLS context, will be used for TLS connections.
+ :param serde: optional "serde". defaults to ``pymemcache.serde.pickle_serde``
+ :param default_noreply: defaults to ``False``

Sorry to seem pedantic about this, it's just to influence the automatic documentation system.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

no biggie =D

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

is there a chance that backend.get_multi() will return None for some missing keys?  that's not expected.  we can filter those out if so

    Traceback (most recent call last):
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/tests/cache/_fixtures.py", line 268, in test_threaded_get_multi
        f()
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/tests/cache/_fixtures.py", line 264, in f
        creator,
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/dogpile/cache/region.py", line 1142, in get_or_create_multi
        async_creator=lambda mutex: async_creator(
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/dogpile/lock.py", line 185, in __enter__
        return self._enter()
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/dogpile/lock.py", line 87, in _enter
        value = value_fn()
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/dogpile/cache/region.py", line 1140, in <lambda>
        lambda: get_value(mangled_key),
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/dogpile/cache/region.py", line 1092, in get_value
        if self._is_cache_miss(value, orig_key):
    File "/home/jenkins/workspace/dogpile_gerrit/9462f37e/dogpile/cache/region.py", line 859, in _is_cache_miss
        elif value.metadata["v"] != value_version:
    AttributeError: 'NoneType' object has no attribute 'metadata'

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

I've got changes coming in re: formatting and trying to get tests to run better so wait for me to do patch # 6

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

thanks all for the reviews / efforts!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494 has been **merged**. Congratulations! :)

**Pull request closed without merging**
