### PR TITLE
Add TLS support for bmemcached

### PR DESCRIPTION
**Pull request by moisesguimaraes**
This is a first scratch to solve #173

At this moment I have the necessary code to make it work. Now I need to add some tests to make sure both TLS and non TLS versions are working properly.

### CODE REVIEW

**Comment by zzzeek** [comment]
nice.  is there any way to add test coverage for this?

**Comment by zzzeek** [comment]
oh sorry you just mentioned that.   I can start running this through jenkins CI as it is now as bmemcached should be exercised at least

**Comment by sqla-tester** [comment]
New Gerrit review created for change 54b71ac349eada115e5607054c7371d8a3f272e2: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by moisesguimaraes** [comment]
@zzzeek how would I best run tox for bmemcached tests only? Right now I'm getting skips on it.

**Comment by zzzeek** [comment]
right now the bmemcached tests are hardcoded to have a lot of skips because the last time I tested some years ago it was too unreliable under concurrency to get through the testing.   to disable these skips do this:

```
diff --git a/tests/cache/test_memcached_backend.py b/tests/cache/test_memcached_backend.py
index f673ac6..0f11c0d 100644
--- a/tests/cache/test_memcached_backend.py
+++ b/tests/cache/test_memcached_backend.py
@@ -93,42 +93,26 @@ class PylibmcDistributedMutexTest(_DistributedMemcachedMutexTest):
     backend = "dogpile.cache.pylibmc"
 
 
-class BMemcachedSkips(object):
-    def test_threaded_dogpile(self):
-        pytest.skip("bmemcached is too unreliable here")
-
-    def test_threaded_get_multi(self):
-        pytest.skip("bmemcached is too unreliable here")
-
-    def test_mutex_threaded_dogpile(self):
-        pytest.skip("bmemcached is too unreliable here")
-
-    def test_mutex_threaded(self):
-        pytest.skip("bmemcached is too unreliable here")
-
-
-class BMemcachedTest(BMemcachedSkips, _NonDistributedMemcachedTest):
+class BMemcachedTest(_NonDistributedMemcachedTest):
     backend = "dogpile.cache.bmemcached"
 
 
 class BMemcachedDistributedWithTimeoutTest(
-    BMemcachedSkips, _DistributedMemcachedWithTimeoutTest
+    _DistributedMemcachedWithTimeoutTest
 ):
     backend = "dogpile.cache.bmemcached"
 
 
-class BMemcachedDistributedTest(BMemcachedSkips, _DistributedMemcachedTest):
+class BMemcachedDistributedTest(_DistributedMemcachedTest):
     backend = "dogpile.cache.bmemcached"
 
 
-class BMemcachedDistributedMutexTest(
-    BMemcachedSkips, _DistributedMemcachedMutexTest
-):
+class BMemcachedDistributedMutexTest(_DistributedMemcachedMutexTest):
     backend = "dogpile.cache.bmemcached"
 
 
 class BMemcachedDistributedMutexWithTimeoutTest(
-    BMemcachedSkips, _DistributedMemcachedMutexWithTimeoutTest
+    _DistributedMemcachedMutexWithTimeoutTest
 ):
     backend = "dogpile.cache.bmemcached"
 

```

**Comment by zzzeek** [comment]
congrats to bmemcached, they all pass now, so we can include the above changes in this patch.
```

tests/cache/test_memcached_backend.py::BMemcachedTest::test_backend_delete PASSED                                                            [ 26%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_backend_delete_nothing PASSED                                                    [ 27%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_backend_get_nothing PASSED                                                       [ 28%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_backend_set_get_value PASSED                                                     [ 28%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_decorated_fn_functionality PASSED                                                [ 29%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_exploding_value_fn PASSED                                                        [ 29%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_creator PASSED                                                            [ 30%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_delete PASSED                                                             [ 30%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_delete_multiple PASSED                                                    [ 31%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_expire PASSED                                                             [ 31%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_get_empty_multiple PASSED                                                 [ 32%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_get_multiple_values PASSED                                                [ 32%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_get_nothing_multiple PASSED                                               [ 33%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_get_or_create_multi_w_should_cache_none PASSED                            [ 34%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_get_zero_multiple_values PASSED                                           [ 34%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_set_get_nothing PASSED                                                    [ 35%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_set_get_value PASSED                                                      [ 35%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_set_multiple_values PASSED                                                [ 36%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_set_zero_multiple_values PASSED                                           [ 36%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_region_set_zero_multiple_values_w_decorator PASSED                               [ 37%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_threaded_dogpile PASSED                                                          [ 37%]
tests/cache/test_memcached_backend.py::BMemcachedTest::test_threaded_get_multi PASSED                                                        [ 38%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_backend_delete PASSED                                      [ 39%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_backend_delete_nothing PASSED                              [ 39%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_backend_get_nothing PASSED                                 [ 40%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_backend_set_get_value PASSED                               [ 40%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_decorated_fn_functionality PASSED                          [ 41%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_exploding_value_fn PASSED                                  [ 41%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_creator PASSED                                      [ 42%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_delete PASSED                                       [ 42%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_delete_multiple PASSED                              [ 43%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_expire PASSED                                       [ 43%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_get_empty_multiple PASSED                           [ 44%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_get_multiple_values PASSED                          [ 45%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_get_nothing_multiple PASSED                         [ 45%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_get_or_create_multi_w_should_cache_none PASSED      [ 46%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_get_zero_multiple_values PASSED                     [ 46%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_set_get_nothing PASSED                              [ 47%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_set_get_value PASSED                                [ 47%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_set_multiple_values PASSED                          [ 48%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_set_zero_multiple_values PASSED                     [ 48%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_region_set_zero_multiple_values_w_decorator PASSED         [ 49%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_threaded_dogpile PASSED                                    [ 50%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedWithTimeoutTest::test_threaded_get_multi PASSED                                  [ 50%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_backend_delete PASSED                                                 [ 51%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_backend_delete_nothing PASSED                                         [ 51%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_backend_get_nothing PASSED                                            [ 52%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_backend_set_get_value PASSED                                          [ 52%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_decorated_fn_functionality PASSED                                     [ 53%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_exploding_value_fn PASSED                                             [ 53%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_creator PASSED                                                 [ 54%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_delete PASSED                                                  [ 54%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_delete_multiple PASSED                                         [ 55%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_expire PASSED                                                  [ 56%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_get_empty_multiple PASSED                                      [ 56%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_get_multiple_values PASSED                                     [ 57%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_get_nothing_multiple PASSED                                    [ 57%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_get_or_create_multi_w_should_cache_none PASSED                 [ 58%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_get_zero_multiple_values PASSED                                [ 58%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_set_get_nothing PASSED                                         [ 59%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_set_get_value PASSED                                           [ 59%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_set_multiple_values PASSED                                     [ 60%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_set_zero_multiple_values PASSED                                [ 60%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_region_set_zero_multiple_values_w_decorator PASSED                    [ 61%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_threaded_dogpile PASSED                                               [ 62%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedTest::test_threaded_get_multi PASSED                                             [ 62%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexTest::test_mutex PASSED                                                     [ 63%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexTest::test_mutex_reentrant_across_keys PASSED                               [ 63%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexTest::test_mutex_threaded PASSED                                            [ 64%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexTest::test_reentrant_dogpile PASSED                                         [ 64%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexWithTimeoutTest::test_mutex PASSED                                          [ 65%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexWithTimeoutTest::test_mutex_reentrant_across_keys PASSED                    [ 65%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexWithTimeoutTest::test_mutex_threaded PASSED                                 [ 66%]
tests/cache/test_memcached_backend.py::BMemcachedDistributedMutexWithTimeoutTest::test_reentrant_dogpile PASSED                              [ 67%]

```

**Comment by moisesguimaraes** [comment]
I'm still getting all skips with:

`tox tests/cache/test_memcached_backend.py::BMemcachedTest`

Anything else I need to turn on?

**Comment by zzzeek** [comment]
is it skipping *all* memcached tests including pylibmc ?   that would mean it cant run the memcached server.   the tests will skip if it can't find the driver, or if it can't connect to the backend.  you can go into the test code and look for "skip", also in _fixtures.py, and just pdb in there to see whats going on.

**Comment by zzzeek** [comment]
also you can try running pifpaf:

    .tox/py37-memcached/bin/pifpaf run memcached sleep 5

that will run the memached server for 5 seconds

**Comment by moisesguimaraes** [comment]
I was missing `-e memcached`

**Comment by moisesguimaraes** [comment]
Got tests working locally, waiting on https://github.com/jd/pifpaf/pull/128 now

**Comment by moisesguimaraes** [comment]
I can also squash everything and work directly on Gerrit if you want.

**Comment by zzzeek** [comment]
openstacker !  OK let me give you contributor perms

**Comment by zzzeek** [comment]
if you can set up your profile in gerrit , uses github auth, then I can add you in.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

havne't been watching this at all so try to get my attention when i need to look at something or fix something

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by moisesguimaraes** [comment]
I had my patch to pifpaf merged today. I'm waiting on a release so I can get the tests running here.

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** (moisesguimaraes) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

this looks good we need to add a changelog file in doc/build/unreleased/

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

so it failed on tests.cache.test_memcached_backend.BMemcachedDistributedWithTimeoutTest.test_threaded_dogpile which is one of the tests that I had commented out as "too unreliable" with bmemcached.     these tests never fail for the pylibmc backend, but it could be timing related especially if bmemcached is pure Python perhaps ?

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

the tests themselves have some silly assumptions let me try to scale them back a bit

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

ok we're good

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/1966 has been **merged**. Congratulations! :)

**Pull request closed without merging**
