### PR TITLE
Exclude installing "tests" package from setup.py

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by zzzeek** [comment]
thanks, the setup.cfg stuff is not well documented IMO

**Comment by mgorny** [comment]
The whole setuptools is badly documented. I've copied this approach from one of setuptools' maintainers' packages, and hammered till it worked ;-).

**Comment by zzzeek** [comment]
"python setup.py bdist_wheel" is still including the tests/ inside the wheel and they are still being installed

**Comment by zzzeek** [comment]
oh there's a cache, nevermind

**Comment by sqla-tester** [comment]
New Gerrit review created for change 559a5c57c922741461d419b73f1aa547e3231110: https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2122

**Comment by mgorny** [comment]
Yeah, you have to clean up/remove `build` directory as otherwise everything in it will be installed.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

excellent!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2122

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2122 has been **merged**. Congratulations! :)

**Comment by CaselIT** [comment]
> 
> 
> oh there's a cache, nevermind

I've lost almost 2 h the other day for this exact same problem 😭 😞

**Pull request closed without merging**
