### PR TITLE
Introduce PBR to package dogpile.cache 

### PR DESCRIPTION
**Pull request by 4383**
Start to use pbr to package dogpile.cache and to avoid version management and other boring stuffs.

Avoid to manage version bumping by using git tags.

Docs version are also retrieve by using pbr sphinx extension.

### CODE REVIEW

**Comment by sqla-tester** [comment]
New Gerrit review created for change ff8d80e0c99d4a80457e326a28f0dd9f8ba05e44: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/dogpile.cache/+/1153

**Comment by zzzeek** [comment]
So at the moment, all the projects released under the sqlalchemy org use the same release process, which is a set of scripts that are currently in the bitbucket.org/sqlalchemyorg part of the organization (free private repos).   I can probably make these public.

I'd like to keep all the projects released under sqlalchemyorg on one consistent system.   PBR brings in a large set of assumptions which I have a vague feeling extend well beyond just the version number.  It's not clear (meaning, I haven't looked) how pbr interacts with the longer term Python standard of [pyproject.toml](https://www.python.org/dev/peps/pep-0518/) that is to replace setup.cfg files eventually.         

pbr makes me uncomfortable because it's not only a third party extension with an uncertain future, it also brings in a large set of assumptions and changes that my projects would now be beholden to staying current with - this adds work for me, just as every time pypi or pip changes something, it adds work.     It is also very strongly linked to the openstack project and I'm not aware that a lot of projects outside of openstack use it.    to quote [its readme](https://pypi.org/project/pbr/):

> PBR is only mildly configurable. The basic idea is that there’s a decent way to run things and if you do, you should reap the rewards, because then it’s simple and repeatable. If you want to do things differently, cool! But you’ve already got the power of Python at your fingertips, so you don’t really need PBR.

I think it's more important that everything under sqlalchemyorg stay on the same system, and it would be a much bigger decision to move SQLAlchemy itself to pbr that needs to take into account the current build system and the long term future of setup.cfg.

**Comment by 4383** [comment]
Your point of view make sense, no problems with that.
Let's me close my PR.

**Comment by 4383** [comment]
I can't abandon these changes on the gerrit side.

**Comment by zzzeek** [comment]
let me give you access!

**Comment by zzzeek** [comment]
OK I think "abandon" is too hard here because the patchset was created by the gerrit bot.  if you create your own patches directly in gerrit you can abandon the ones you made yourself.

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1153 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
