### PR TITLE
Added support for MongoDB

### PR DESCRIPTION
**Pull request by thestick613**
All the tests pass, everything seems to work.
Not sure if i missed anything, but i based this on the redis backend file.

### CODE REVIEW

**Comment by zzzeek** [comment]
OK this looks totally great but unfortunately I can't maintain it or do any test suite support for it.      any reason you can't release this as its own package and set up travis etc. for it?

**Comment by thestick613** [comment]
So are you suggesting i should fork dogpile.cache into something else which also supports mongo?

**Comment by zzzeek** [comment]
> So are you suggesting i should fork dogpile.cache into something else which also supports mongo?

no, you would release this code as dogpile-mongodb and use the [setuptools entrypoints](https://dogpilecache.sqlalchemy.org/en/latest/usage.html#creating-backends) so that someone can install your package and dogpile.cache at the same time and the 'dogpile-mongodb' backend will be available.  

example 3rd party backends:

https://pypi.org/project/dogpile-filesystem/
https://pypi.org/project/dogpile-elasticache/
https://pypi.org/project/dogpile_cache_native_redis/
https://pypi.org/project/dogpile_appengine/

setuptools entrypoints: https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins

**Comment by thestick613** [comment]
Oh, ok.

**Comment by zzzeek** [comment]
Sorry, your plugin will get better care if it's outside of dogpile as I don't have much time to maintain dogpile at all right now.

**Pull request closed without merging**
